services:
  training-fruits:
    image: docker.frappet.com/training/training-fruits:latest
    container_name: training-fruits
    # image: docker.frappet.com/training/oom_be:latest
    environment:
      DATABASE_URL: file:./dev.db
      # DATABASE_URL: file:/app/data/dev.db  # เปลี่ยนให้ชี้ไปที่ path ใน volume
      TZ: Asia/Bangkok
      DEBUG: "*"
      # - TZ=Asia/Bangkok
    ports:
      - 8001:80
    # deploy:
    #   mode: replicated
    #   replicas: 3

    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.fe.rule=Host(`fe.oom.home`)"
    # networks:
    #  - traefik
    build:
      context: .
    command: >
        sh -c "npx prisma generate && npx prisma migrate deploy && npm start"
    volumes:
      - sqlite_data:/app/data

volumes:
  sqlite_data: {}