services:
  training-fruits:
    image: docker.frappet.com/training/training-fruits:latest
    container_name: training-fruits
    # image: docker.frappet.com/training/oom_be:latest
    environment:
      # DATABASE_URL: file:./prisma/dev.db
      # TZ: Asia/Bangkok
      - TZ=Asia/Bangkok
    ports:
      - 8001:80
    # volumes:
    #   - ./data:/app/data
    # deploy:
    #   mode: replicated
    #   replicas: 3

    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.fe.rule=Host(`fe.oom.home`)"
    # networks:
    #  - traefik
    build:
      context: .
    command: >
      sh -c "npx prisma generate && npm start"