services:
  myexpress:
    image: docker.frappet.com/training/training-fruits:latest
    container_name: training-fruits
    # image: docker.frappet.com/training/oom_be:latest
    ports:
      - 8001:80
    environment:
      - TZ=Asia/Bangkok
    # deploy:
    #   mode: replicated
    #   replicas: 3

    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.fe.rule=Host(`fe.oom.home`)"
    # networks:
    #  - traefik